import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import { useState, useEffect } from 'react';
import axios from 'axios';
const Home = ()=> {

  const [data, setData] = useState([]);

  useEffect(()=>{
    getData();
  }, []);

  const getData = async()=>{
    const response = await axios.get(process.env.NEXT_PUBLIC_API_URL);
    if(response.status === 200){
      setData(response.data);
    }
  };

  
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="nav">
        <a href="" className="active">Home</a>
        <a href="">News</a>
        <a href="">Contact</a>
        <a href="">About</a>
        <a href="/login" className="logout">Login</a>
      </div>
      <div style={{marginTop:"15px"}}>
        <table className="styled_table">
          <thead>
            <tr>
              <th style={{textAlign:"center"}}>No.</th>
              <th style={{textAlign:"center"}}>Region Name</th>
              <th style={{textAlign:"center"}}>Action(s)</th>
            </tr>
          </thead>
          <tbody>
            {data && data.map((item, index) => {
              return (
                <tr key={index}>
                  <th scope='row'>{index + 1}</th>
                  <td>{item.regionname}</td>
                  <td><a href={`/district/${item.regionname}`} className="btn_view">View</a></td>
                </tr>
              )
            })}
          </tbody>
        </table>
      </div>
    </div>
  )
}

export default Home;
