import Head from 'next/head';
import Image from 'next/image';
import { useState, useEffect } from 'react';
import { useRouter } from 'next/router';
import axios from 'axios';
const District = ()=> {

  const [data, setData] = useState([]);

  const router = useRouter();
  const { district } = router.query;

  useEffect(()=>{
    if(district){
      getData(district);
    }
  }, [district]);

  const getData = async()=>{
    const response = await axios.get(`${process.env.NEXT_PUBLIC_API_URL}/district/${district}`);
    if(response.status === 200){
      setData(response.data);
    }
  };

  
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="nav">
        <a href="/" className="active">Home</a>
        <a href="">News</a>
        <a href="">Contact</a>
        <a href="">About</a>
        <a href="/login" className="logout">Login</a>
      </div>
      <div style={{marginTop:"15px"}}>
        <table className="styled_table">
          <thead>
            <tr>
              <th style={{textAlign:"center"}}>No.</th>
              <th style={{textAlign:"center"}}>District Name</th>
            </tr>
          </thead>
          <tbody>
            {data && data.map((item, index) => {
              return (
                <tr key={index}>
                  <th scope='row'>{index + 1}</th>
                  <td>{item.districtname}</td>
                </tr>
              )
            })}
          </tbody>
        </table>
      </div>
    </div>
  )
}

export default District;